### ISSUE TITLE
Extracting Utils

### ISSUE THREAD

**Issue by se3000** [cryptape/ruby-ethereum#3]
Hi, first thanks for all the great work on this gem.

I needed a gem that was a little lighter weight, really just for signing transactions, ideally without having to install extra non-ruby stuff like Serpent and libsecp256k1. So, I put [this gem](https://github.com/se3000/ethereum-tx) together. To get this done, I pulled some code from your gem. Specifically, the `Utils` class, but a bit of other stuff too(like RLP, the related `Sedes` class, and some `Constants`).

Would you be open to moving Ethereum::Utils into it's own gem? I'd be willing to do the work of moving it over, but figured you might want to control the gem as you wrote it to begin with.

**Comment by janx** [comment]
@se3000 thanks for pinging, that makes sense.

I'd like to create the repo, any suggestion on the repo name? ruby-ethereum-{utils,base,essentials,etc.}?

**Comment by se3000** [comment]
Thanks for asking. [Tough question](https://twitter.com/codinghorror/status/506010907021828096), but I guess I'd lean towards "base" then "utils."

**Comment by janx** [comment]
Cool. I created https://github.com/janx/ruby-ethereum-base.

:beers:

**Comment by alexhanh** [comment]
Could you push the latest version to https://github.com/janx/ruby-ethereum-base? It's currently empty.

**Comment by se3000** [comment]
Hey, it's published [over here](https://github.com/se3000/ruby-ethereum-base). I've been messing around with it, trying to get the name spacing to work smoothly between gems, like [we talked about](https://github.com/se3000/ethereum-tx/issues/1). Sorry it's taking so long, trying to figure out a simple answer without having to rename everything.

Right now I'm leaning towards making each gem have a separate namespace. That's much more common, and easier to deal with. It's definitely possible to share a namespace, but it takes some coordination(tougher in decentralized world) and a specific set up. (see RSpec for a good example of a collection of gems sharing a namespace)

@janx @alexhanh do you have any thoughts?

**Comment by alexhanh** [comment]
I agree that in an ideal world, we would have the `::Ethereum` namespace for the foundational base Ethereum Ruby libraries. But as you say, we cannot have control over everything and predict what future repositories and actors will do (ie. pollute the `::Ethereum` namespace irresponsibly), so IMHO the best we can do is have a defensive naming strategy.

Luckily, on the other hand, there's only a handful of Ruby related Ethereum gems ([Rubygems](https://rubygems.org/search?utf8=%E2%9C%93&query=ethereum) and [Github](https://github.com/search?l=&p=3&q=ethereum+language%3ARuby&ref=advsearch&type=Repositories&utf8=%E2%9C%93)):

- [ethereum](https://github.com/DigixGlobal/ethereum-ruby) `::Ethereum`
- [ruby-ethereum](https://github.com/janx/ruby-ethereum) `::Ethereum`
- [ethereum-tx](https://github.com/se3000/ethereum-tx) `::Ethereum`
- [ethereum_client](https://github.com/dmxhZGp1c2hh/ethereum_client) `::EthereumClient`
- [ethereum-base](https://github.com/se3000/ruby-ethereum-base) `::Ethereum`
- [reth](https://github.com/janx/reth) `::Reth`
- [jeth](https://github.com/alexhanh/jeth) `::Jeth`

Thus, I'd probably just leave `::Ethereum` alone and use `::EthereumTx`, `::EthereumBase`, etc. Or perhaps even the shorter `::EthTx`, `::EthBase`, etc.

So +1 to separate namespace for each gem.

**Comment by janx** [comment]
Thanks @se3000 @alexhanh 

I prefer `::Ethereum`, it's more natural. Maybe we can take the chance to create a collaborative like https://github.com/ethereumjs, since we have quite a few ruby developers now. It will cost a little more time but definitely worth doing I think.

**Comment by JikkuJose** [comment]
@janx Yes! I too think we need an EthereumRb collaborative! It will help consolidate our efforts!

**Comment by se3000** [comment]
For now, I changed my gem to live in a different namespace, [Eth](https://github.com/se3000/ruby-eth). It was causing problems for people already. I think ruby might be a little less lenient about sharing namespaces than JavaScript. I'd be happy to change it in the future if we can coordinate a collaborative, and ensure that certain combinations of gems don't end up clobbering each other.

@janx I saw you'll be at DevCon2, I'm planning on attending. @tymat and @alexhanh will you be there? Might be worth talking in person.

**Comment by alexhanh** [comment]
@se3000 looks great! Haven't decided yet about DC2, but if I manage to come, would love to meet. :)

**Comment by janx** [comment]
@se3000 @alexhanh yes I'll give a talk, it would be great to meet you guys there, we can have a discuss on the collaborative. Please let me know if you decided to come :)

**Comment by u2** [comment]
It's a great idea to create EthereumRb collaborative! And I think we can also extract ethereumrb-abi, and ethereumrb-vm as a single gem, like ethereumjs.

**Comment by se3000** [comment]
Closing this, it's a matter of moving the gem forward now. Thanks!
